package edu.ntnu.idi.idatt.event;

public enum GameEventType {
  BOARD_CREATED,
  DICE_CREATED,
  PLAYER_ADDED,
  DICE_ROLLED,
  PLAYER_MOVED,
  ACTION_PERFORMED,
  TURN_CHANGED,
  GAME_OVER,
  LADDER_CLIMBED,
  CHUTE_SLID
}